# This file was generated by GoReleaser. DO NOT EDIT.
cask "agsy" do
  version "0.1.0-rc1"

  on_macos do
    on_arm do
      sha256 "e03b4c2ff8134e4d1a975acda63837badd0ba69bf630b748386e87998968eb25"
      url "https://github.com/IngSquared99/agent-sync/releases/download/v#{version}/agsy_mac_apple_silicon.tar.gz"
    end
    on_intel do
      sha256 "da9622a36887f52620e64a89501ee748b6ff40170b25cd2d6d952cbbd5fd2085"
      url "https://github.com/IngSquared99/agent-sync/releases/download/v#{version}/agsy_mac_intel.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "95233766c8d8b0afc071079f71bd12105e1eec1345dc4619276c7634ef90a26f"
      url "https://github.com/IngSquared99/agent-sync/releases/download/v#{version}/agsy_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8ed622fcf1b4458e2d59b5def8942e5d835029032aac8259ba1ddb20e4c43d75"
      url "https://github.com/IngSquared99/agent-sync/releases/download/v#{version}/agsy_linux_x64.tar.gz"
    end
  end

  name "agsy"
  desc "Sync AI rules to every tool"
  homepage "https://github.com/IngSquared99/agent-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agsy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agsy"]
    end
  end

  # No zap stanza required
end
