# This file was generated by GoReleaser. DO NOT EDIT.
cask "agsy" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "9fdbbca35a414b415ca251f11f1e17b2242896cffc78f5b2641d3bf61167b631"
      url "https://github.com/IngSquared99/agent-sync/releases/download/v#{version}/agsy_mac_apple_silicon.tar.gz"
    end
    on_intel do
      sha256 "8795ac99b36d9d7600c407b9e6a62d1ecd02672a06904d38e59d2a518cf4fb89"
      url "https://github.com/IngSquared99/agent-sync/releases/download/v#{version}/agsy_mac_intel.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "684ad488d917ff67ffb5e48a8038ce92688298d4267c7fe41993480553bfe4b9"
      url "https://github.com/IngSquared99/agent-sync/releases/download/v#{version}/agsy_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c9baf590ec64174f8938c40ccdf06947f6fddf74729eed1db294e180a1bb4344"
      url "https://github.com/IngSquared99/agent-sync/releases/download/v#{version}/agsy_linux_x64.tar.gz"
    end
  end

  name "agsy"
  desc "Sync AI rules to every tool"
  homepage "https://github.com/IngSquared99/agent-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agsy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agsy"]
    end
  end

  # No zap stanza required
end
